import React, { useState } from 'react';
import NeumorphicCard from '../components/common/NeumorphicCard';
import NeumorphicSwitch from '../components/common/NeumorphicSwitch';
import NeumorphicButton from '../components/common/NeumorphicButton';
import { isSupabaseConfigured } from '../functions/services/supabaseClient';

/**
 * Pantalla de Ajustes, Configuración de Tema y Supabase
 */
export function SettingsScreen({ theme = 'light', onToggleTheme }) {
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [copiedSql, setCopiedSql] = useState(false);

  const supabaseSqlSchema = `-- Tabla de Tasas Históricas para Supabase
CREATE TABLE IF NOT EXISTS exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recorded_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  bcv_usd NUMERIC(10, 4) NOT NULL,
  bcv_eur NUMERIC(10, 4) NOT NULL,
  usdt NUMERIC(10, 4),
  paralelo NUMERIC(10, 4),
  source TEXT DEFAULT 'BCV'
);

-- Habilitar lectura pública (Row Level Security)
ALTER TABLE exchange_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir lectura publica" ON exchange_rates FOR SELECT USING (true);`;

  const copySql = () => {
    navigator.clipboard?.writeText(supabaseSqlSchema);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  return (
    <div className="container-fluid max-width-lg pb-5">
      <h4 className="fw-bold mb-1 text-dark">Ajustes del Sistema</h4>
      <p className="text-secondary small mb-4">
        Personalización visual, sincronización con Supabase y preferencias de divisas.
      </p>

      <div className="row g-4">
        {/* Tarjeta de Personalización y Apariencia */}
        <div className="col-12 col-md-6">
          <NeumorphicCard className="p-4 h-100">
            <h6 className="fw-bold text-dark mb-3">Apariencia y Tema</h6>

            <div className="d-flex justify-content-between align-items-center py-2 border-bottom border-light-subtle">
              <div>
                <div className="fw-semibold small text-dark">Modo Oscuro (Dark Theme)</div>
                <div className="text-muted small" style={{ fontSize: '0.72rem' }}>
                  {theme === 'dark' ? 'Estilo Neumórfico Dark activo' : 'Estilo Neumórfico Claro activo'}
                </div>
              </div>
              <NeumorphicSwitch
                checked={theme === 'dark'}
                onChange={onToggleTheme}
              />
            </div>

            <div className="d-flex justify-content-between align-items-center py-3">
              <div>
                <div className="fw-semibold small text-dark">Actualización Automática</div>
                <div className="text-muted small" style={{ fontSize: '0.72rem' }}>
                  Recargar tasas cada 5 minutos
                </div>
              </div>
              <NeumorphicSwitch
                checked={autoRefresh}
                onChange={setAutoRefresh}
              />
            </div>
          </NeumorphicCard>
        </div>

        {/* Tarjeta de Seguridad y Arquitectura */}
        <div className="col-12 col-md-6">
          <NeumorphicCard className="p-4 h-100">
            <h6 className="fw-bold text-dark mb-3">Verificación de Arquitectura</h6>

            <div className="d-flex align-items-center gap-2 mb-2 text-success small fw-semibold">
              <i className="bi bi-check-circle-fill"></i>
              <span>HTTPS Forzado en todas las conexiones</span>
            </div>

            <div className="d-flex align-items-center gap-2 mb-2 text-success small fw-semibold">
              <i className="bi bi-check-circle-fill"></i>
              <span>Fetch API nativa (cero dependencias de Axios)</span>
            </div>

            <div className="d-flex align-items-center gap-2 mb-2 text-success small fw-semibold">
              <i className="bi bi-check-circle-fill"></i>
              <span>Soporte Multidivisa: Euro, USDT, BCV y Paralelo</span>
            </div>

            <div className="d-flex align-items-center gap-2 text-success small fw-semibold">
              <i className="bi bi-check-circle-fill"></i>
              <span>Diseño Neumórfico Responsivo (PC y Celular)</span>
            </div>
          </NeumorphicCard>
        </div>

        {/* Tarjeta de Estado de Supabase */}
        <div className="col-12">
          <NeumorphicCard className="p-4">
            <div className="d-flex justify-content-between align-items-center mb-3">
              <div className="d-flex align-items-center gap-3">
                <div
                  className="rounded-circle d-flex align-items-center justify-content-center"
                  style={{
                    width: '44px',
                    height: '44px',
                    background: isSupabaseConfigured ? 'rgba(16, 185, 129, 0.15)' : 'rgba(245, 158, 11, 0.15)',
                    color: isSupabaseConfigured ? '#059669' : '#d97706',
                    fontSize: '1.3rem',
                  }}
                >
                  <i className={`bi ${isSupabaseConfigured ? 'bi-database-fill-check' : 'bi-database-exclamation'}`}></i>
                </div>
                <div>
                  <h6 className="mb-0 fw-bold">Conexión con Supabase</h6>
                  <span className="small text-secondary">
                    {isSupabaseConfigured
                      ? 'Conectado a tu proyecto de Supabase'
                      : 'Operando con almacenamiento local y datos en tiempo real'}
                  </span>
                </div>
              </div>

              <span className={`badge rounded-pill ${isSupabaseConfigured ? 'bg-success' : 'bg-warning text-dark'} px-3 py-2 fw-bold`}>
                {isSupabaseConfigured ? 'ACTIVO' : 'PENDIENTE'}
              </span>
            </div>

            <p className="small text-muted mb-3">
              Para vincular tu propia base de datos de Supabase, agrega las credenciales en tu archivo <code>.env</code>:
            </p>

            <pre className="p-3 rounded-3 neu-card-pressed small mb-3 overflow-x-auto" style={{ fontSize: '0.8rem' }}>
{`VITE_SUPABASE_URL=https://tu-proyecto.supabase.co
VITE_SUPABASE_ANON_KEY=tu-clave-anonima-publica`}
            </pre>

            <div className="d-flex justify-content-between align-items-center pt-3 border-top border-light-subtle">
              <span className="small text-secondary fw-semibold">Script SQL para crear la tabla:</span>
              <NeumorphicButton
                variant="default"
                icon={copiedSql ? 'bi-check-lg text-success' : 'bi-clipboard'}
                onClick={copySql}
                className="py-1 px-3 small"
              >
                {copiedSql ? '¡Copiado!' : 'Copiar SQL'}
              </NeumorphicButton>
            </div>
          </NeumorphicCard>
        </div>
      </div>
    </div>
  );
}

export default SettingsScreen;
